name: "Build"

on:
  pull_request:
  push:
    branches: [build]

jobs:
  build-windows:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v23

      - name: Build and Upload Artifact
        run: nix build -L --show-trace .#windows.installer

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: windows-installer
          path: ./result

  download-artifact:
    runs-on: ubuntu-latest
    needs: build-windows
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v3
        with:
          name: windows-installer
          path: ./downloaded-artifacts
